version: 2
run:
  go: "1.23"
  timeout: 5m
linters:
  enable-all: true
  disable:
    - depguard
    - err113
    - errcheck
    - exhaustruct
    - gochecknoglobals
    - gochecknoinits
    - godox
    - gosmopolitan
    - ireturn
    - lll
    - mnd
    - nlreturn
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - tagliatelle
    - testpackage
    - varnamelen
    - wrapcheck
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/uberspace-community/terraform-provider-uberspace)